services:
  ansible-actualizer.dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-actualizer.dev
    working_dir: /app
    volumes:
      - .:/app
    user: "1000:1000"
    tty: true