---
- name: Actualize ABS
  hosts: webservers
  gather_facts: false
  vars:
    config_path: "/var/www/abs/config.js" # ABS config file

  pre_tasks:
    - name: Check if host available for connection
      ping:
      register: ping_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Remove unreachable hosts out of execution
      meta: end_host
      when: ping_result.unreachable is defined and ping_result.unreachable

  tasks:
    - name: Ensure that {{ config_path }} exist
      stat:
        path: "{{ config_path }}"
      register: config_file

    - name: Read {{ config_path }}
      slurp:
        src: "{{ config_path }}"
      when: config_file.stat.exists
      register: file_content

    - name: Extract dialog360 block from {{ config_path }}
      set_fact:
        dialog_block: "{{ (decoded_content | regex_search('dialog360:\\s\\{[^\\}]*\\}', '\\0')) }}"
      when: config_file.stat.exists
      vars:
        decoded_content: "{{ file_content.content | b64decode }}"

    - name: Extract dialog360.use from dialog360 block
      set_fact:
        dialog_use: "{{ (dialog_block | regex_search(\"use:\\s(true|false)\", '\\1'))[0] | lower | bool }}"
      when: dialog_block is defined

    - name: Debug dialog360.use
      debug:
        var: dialog_use

    - name: Remove non dialog360 hosts out of execution
      meta: end_host
      when: dialog_use is defined and not dialog_use

    - name: Extract dialog360.api_key from dialog360 block
      set_fact:
        dialog_api_key: "{{ (dialog_block | regex_search(\"api_key:\\s'([^']+)'\", '\\1'))[0] }}"

    - name: Make a GET request to dialog360 health_status endpoint
      uri:
        url: "https://waba-v2.360dialog.io/health_status"
        method: GET
        headers:
          D360-API-KEY: "{{ dialog_api_key }}"
          Content-Type: "application/json"
        return_content: true
      register: health_check_response
      failed_when: false

    - name: Debug health_status response
      debug:
        var: health_check_response
