---
- name: Actualize ABS
  hosts: webservers
  gather_facts: false
  vars:
    config_path: /var/www/abs/config.js # ABS config file

  pre_tasks:
    - name: Check if host available for connection
      ping:
      register: ping_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Remove unreachable hosts out of execution
      meta: end_host
      when: ping_result.unreachable is defined and ping_result.unreachable

  tasks:
    - name: Ensure that {{ config_path }} exist
      stat:
        path: "{{ config_path }}"
      register: config_file

    - name: Read {{ config_path }}
      slurp:
        src: "{{ config_path }}"
      when: config_file.stat.exists
      register: file_content

    - name: Extract dialog360 block from {{ config_path }}
      set_fact:
        dialog_block: "{{ (decoded_content | regex_search('dialog360:\\s\\{[^\\}]*\\}', '\\0')) }}"
      when: config_file.stat.exists
      vars:
        decoded_content: "{{ file_content.content | b64decode }}"

    - name: Show dialog360 block
      debug:
        msg: "{{ dialog_block }}"
      when: config_file.stat.exists and dialog_block is defined