---
- name: Cleaning up the stand after work
  hosts: localhost
  gather_facts: false

  vars:
    decrypted_key_dir: "./tmp/"      # Directory with saved decrypted ssh_private_key
    decrypted_key_path: "{{ decrypted_key_dir }}/id_rsa"

  tasks:
    - name: Remove decrypted ssh key file
      file:
        path: "{{ decrypted_key_path }}"
        state: absent
