---
- name: Preparing the stand for work
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../vault/vault.yml" # Encrypted ssh_private_key

  vars:
    decrypted_key_dir: "./tmp/"      # Directory to save decrypted ssh_private_key
    decrypted_key_path: "{{ decrypted_key_dir }}/id_rsa"

  tasks:
    - name: Ensure the directory to save decrypted key exists
      file:
        path: "{{ decrypted_key_dir }}"
        state: directory
        mode: '0700'

    - name: Write decrypted ssh key to file
      copy:
        content: "{{ ssh_private_key }}"
        dest: "{{ decrypted_key_path }}"
        mode: '0600'